### ISSUE TITLE
Bundler.require

### ISSUE THREAD

**Issue by Integralist** [BBC-News/chintz-ruby#1]
It's usually more conventional in Ruby to be explicit, and only require the libraries that you need rather than a blanket (and rather ambiguous) `Bundler.require` command (i.e. as seen in your `config.ru` file)

**Comment by Integralist** [comment]
Also, as we're talking about `config.ru` it would be better to update your Ruby `LOAD_PATH` variable to include your `/lib` folder; like so `$: << File.join(File.dirname(__FILE__), "lib")`

This would allow you to do (inside `webapp.rb`) `require 'parser'` rather than the long form `require './lib/parser.rb'`

**Comment by jcleveley-zz** [comment]
@Integralist Thanks Mark, keep it coming!
